name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master  # Change to your main branch if needed

jobs:
  deploy:
    name: Deploy Dart Shelf App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print Project ID Info
        run: |
          echo "Project ID starts with: ${FIREBASE_PROJECT_ID:0:3}"
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Build and Push Docker Image (Artifact Registry)
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev
          docker build \
            --build-arg FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} \
            -t us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/dart-shelf-repo/dart-shelf-app .
          docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/dart-shelf-repo/dart-shelf-app

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy dart-shelf-app \
            --image us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/dart-shelf-repo/dart-shelf-app \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}"
 